apiVersion: apps/v1
kind: Deployment
metadata:
  name: crappyurl-server
  labels:
    app: crappyurl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crappyurl
  template:
    metadata:
      labels:
        app: crappyurl
    spec:
      containers:
      - name: crappyurl-server
        image: gcr.io/crappy-url/crappyurl-node:v4
        ports:
        - containerPort: 9999
        env:
        - name: DOMAIN
          value: http://34.69.165.82:8080
---
apiVersion: v1
kind: Service
metadata:
  name: crappyurl-service
  labels:
    app: crappyurl
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 9999
    name: http
  selector:
    app: crappyurl
